dados_album = {
    "México": [11],
    "África do Sul": [11],
    "Suiça": [14, 14],
    "Brasil": [1],
    "Marrocos": [2],
    "Haiti": [9],
    "USA": [17],
    "Paraguai": [13],
    "Australia": [14, 16, 20],
    "Costa do Marfim": [20],
    "Holanda": [14],
    "Japão": [20],
    "Egito": [18],
    "Espanha": [18],
    "Arábia Saudita": [12],
    "Uruguai": [18],
    "França": [11],
    "Argentina": [5, 9],
    "Áustria": [4, 9, 14],
    "Portugal": [7],
    "Colombia": [1],
    "Inglaterra": [3],
    "Oficial da Coca Cola": [12]
}